### ISSUE TITLE
"More filters" doesn't work correct with radio buttons

### ISSUE THREAD

**Issue by ylazakovich** [allure-framework/allure3#18]
**To Reproduce**
1. Go to https://allure-framework.github.io/allure3/
2. Click on 'More filters'
3. Try to click on any radio button 

**Expected behavior**
I expect while clicking at radio button filter will be enabled but nothing happens

**Screenshots**
<img width="950" alt="image" src="https://github.com/user-attachments/assets/103e87f3-671c-4f0a-8132-d0d36e53a559" />

**Comment by todti** [comment]
@ylazakovich thank you!
